In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go

# pio.renderers.default = "svg" # this line must be commented if working on colab

In [18]:
# !file "Speed+Dating+Data.csv"

In [19]:
# with open('Speed+Dating+Data.csv') as f:
#     print(f)

In [20]:
df = pd.read_csv("Speed+Dating+Data.csv", encoding='windows-1252')  # dérivé de encoding='latin-1'
df

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,552,22.0,1,44,2,21,22,14,10.0,5,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0
8374,552,22.0,1,44,2,21,22,13,10.0,4,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0
8375,552,22.0,1,44,2,21,22,19,10.0,10,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0
8376,552,22.0,1,44,2,21,22,3,10.0,16,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0
8377,552,NaN,1,44,2,21,22,2,10.0,15,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Columns: 195 entries, iid to amb5_3
dtypes: float64(174), int64(13), object(8)
memory usage: 12.5+ MB

In [22]:
for i, col in enumerate(df.columns):
    print(f"{i}: {col}")

0: iid
1: id
2: gender
3: idg
4: condtn
5: wave
6: round
7: position
8: positin1
9: order
10: partner
11: pid
12: match
13: int_corr
14: samerace
15: age_o
16: race_o
17: pf_o_att
18: pf_o_sin
19: pf_o_int
20: pf_o_fun
21: pf_o_amb
22: pf_o_sha
23: dec_o
24: attr_o
25: sinc_o
26: intel_o
27: fun_o
28: amb_o
29: shar_o
30: like_o
31: prob_o
32: met_o
33: age
34: field
35: field_cd
36: undergra
37: mn_sat
38: tuition
39: race
40: imprace
41: imprelig
42: from
43: zipcode
44: income
45: goal
46: date
47: go_out
48: career
49: career_c
50: sports
51: tvsports
52: exercise
53: dining
54: museums
55: art
56: hiking
57: gaming
58: clubbing
59: reading
60: tv
61: theater
62: movies
63: concerts
64: music
65: shopping
66: yoga
67: exphappy
68: expnum
69: attr1_1
70: sinc1_1
71: intel1_1
72: fun1_1
73: amb1_1
74: shar1_1
75: attr4_1
76: sinc4_1
77: intel4_1
78: fun4_1
79: amb4_1
80: shar4_1
81: attr2_1
82: sinc2_1
83: intel2_1
84: fun2_1
85: amb2_1
86: shar2_1
87: attr3_1
88: sinc3_1
89: fun3_1
90: intel3_1
91: amb3_1
92: attr5_1
93: sinc5_1
94: intel5_1
95: fun5_1
96: amb5_1
97: dec
98: attr
99: sinc
100: intel
101: fun
102: amb
103: shar
104: like
105: prob
106: met
107: match_es
108: attr1_s
109: sinc1_s
110: intel1_s
111: fun1_s
112: amb1_s
113: shar1_s
114: attr3_s
115: sinc3_s
116: intel3_s
117: fun3_s
118: amb3_s
119: satis_2
120: length
121: numdat_2
122: attr7_2
123: sinc7_2
124: intel7_2
125: fun7_2
126: amb7_2
127: shar7_2
128: attr1_2
129: sinc1_2
130: intel1_2
131: fun1_2
132: amb1_2
133: shar1_2
134: attr4_2
135: sinc4_2
136: intel4_2
137: fun4_2
138: amb4_2
139: shar4_2
140: attr2_2
141: sinc2_2
142: intel2_2
143: fun2_2
144: amb2_2
145: shar2_2
146: attr3_2
147: sinc3_2
148: intel3_2
149: fun3_2
150: amb3_2
151: attr5_2
152: sinc5_2
153: intel5_2
154: fun5_2
155: amb5_2
156: you_call
157: them_cal
158: date_3
159: numdat_3
160: num_in_3
161: attr1_3
162: sinc1_3
163: intel1_3
164: fun1_3
165: amb1_3
166: shar1_3
167: attr7_3
168: sinc7_3
169: intel7_3
170: fun7_3
171: amb7_3
172: shar7_3
173: attr4_3
174: sinc4_3
175: intel4_3
176: fun4_3
177: amb4_3
178: shar4_3
179: attr2_3
180: sinc2_3
181: intel2_3
182: fun2_3
183: amb2_3
184: shar2_3
185: attr3_3
186: sinc3_3
187: intel3_3
188: fun3_3
189: amb3_3
190: attr5_3
191: sinc5_3
192: intel5_3
193: fun5_3
194: amb5_3

In [23]:
# ajout colonne label genre et race

df["gender_label"] = df["gender"].map({0: "Femme", 1: "Homme"})
df["race_label"] = df["race"].map({1: "Noir", 2: "Blanc", 3:"Hispanique/Latino", 4: "Asiatique", 5: "Amérindien", 6: "Autre"})

In [24]:
# visualisation nb Hommes Femmes par race

fig_gender_race = px.histogram(df, x="race_label", color="gender_label")

fig_gender_race.update_layout(xaxis_title='Race', yaxis_title="Nombre")
fig_gender_race.update_layout(legend_title_text='Genre')
fig_gender_race.show()

- Comparer les couleurs ensemble (variables attributs), voir évolution dans le tps, y a-t-il des diffs selon revenus, études, religion, race, genre ?
- Voir les variables "uniques"

In [25]:
#a = len(df.loc[df["wave"].between(6, 9)].groupby("iid"))
#a

In [26]:
# Les vagues 6 à 9 ne vont pas être écartées car représentent 19% du dataset.

nb_participant_total = len(df.groupby('iid'))
nb_participant_w_6_9 = len(df.loc[(df["wave"] >= 6) & (df["wave"] <= 9)].groupby("iid")) # len(df.loc[df["wave"].between(6, 9)].groupby("iid"))
print(f"nb de participants : {nb_participant_total}, nb de participants vagues 6 à 9 : {nb_participant_w_6_9}, vagues 6 à 9 représentent {nb_participant_w_6_9/nb_participant_total:.2%} du dataset")

nb de participants : 551, nb de participants vagues 6 à 9 : 102, vagues 6 à 9 représentent 18.51% du dataset

In [27]:
# Test pour hamoniser les vagues 6 à 9. 6 à 60 si x10, 1 => 0 et 10 => 9, amplitude 10 - 1 = 9

six_att = [5, 7, 8, 1, 6, 8]
decal = [x - 1 for x in six_att]
print(decal)
rescal = [x * 100 / 9 for x in decal]
print(rescal)
somme = sum(rescal)
print(somme)
renorm = [x * 100 / somme for x in rescal]
print(renorm)
print(f"somme : {sum(renorm)}")
arrond = [round(x, 2) for x in renorm]
print(arrond)
print(f"somme arrondie : {sum(arrond)}")

[4, 6, 7, 0, 5, 7]
[44.44444444444444, 66.66666666666667, 77.77777777777777, 0.0, 55.55555555555556, 77.77777777777777]
322.22222222222223
[13.793103448275861, 20.689655172413794, 24.137931034482758, 0.0, 17.24137931034483, 24.137931034482758]
somme : 100.0
[13.79, 20.69, 24.14, 0.0, 17.24, 24.14]
somme arrondie : 100.0

In [28]:
# les vagues 6 à 9 vont être harmonisées. min 6 à max 60 si x10, 1 => 0 et 10 => 9, amplitude 10 - 1 = 9

df1 = df.copy()

wav6_9 = df1["wave"].between(6, 9)
df1[wav6_9]

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3,gender_label,race_label
1846,132,1.0,0,1,1,6,5,2,2.0,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Femme,Blanc
1847,132,1.0,0,1,1,6,5,2,2.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Femme,Blanc
1848,132,1.0,0,1,1,6,5,2,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Femme,Blanc
1849,132,1.0,0,1,1,6,5,2,2.0,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Femme,Blanc
1850,132,1.0,0,1,1,6,5,2,2.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Femme,Blanc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3403,233,20.0,1,40,2,9,20,20,11.0,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Homme,Asiatique
3404,233,20.0,1,40,2,9,20,1,11.0,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Homme,Asiatique
3405,233,20.0,1,40,2,9,20,7,11.0,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Homme,Asiatique
3406,233,20.0,1,40,2,9,20,10,11.0,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Homme,Asiatique
3407,233,20.0,1,40,2,9,20,8,11.0,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Homme,Asiatique

In [29]:
# Voir quelles colonnes normaliser, pour les vagues de 6 - 9.
# A norm : attr4_1, attr3_1, attr3_s, attr3_2, attr4_2, attr4_3, attr2_3, attr3_3, attr_0, attr 
# déjà norm :pf_o_att, attr1_1, attr2_1, attr1_s, attr1_2, attr2_2, attr1_3,
# absent : attr5_1, attr7_2 , attr5_2, attr7_3, attr5_3 

# autres vagues sur 100 : pf_o_att, attr1_1, attr2_1, att1_2, attr1_3
# 1 à 10 : attr_o, attr3_1, attr, attr3_2, attr3_3

# pareil : pf_o_att, attr_o, attr_1, attr2_1, attr3_1, 

# => il n'y aurait que ces 5x6-2 colonnes à renormaliser, les autres étant notées sur la même échelle, des erreurs ds dataset des notes de 12/10 par ex... attr3_3, ligne 3130...
# A norm : attr4_1, attr3_s, attr4_2, attr4_3, attr2_3, 

verif_val = ["pf_o_att", "attr1_1", "attr4_1", 'attr2_1', 'attr3_1', 'attr5_1', "attr_o", "attr", "attr1_s", "attr3_s", "attr7_2", "attr1_2", "attr4_2", "attr2_2",
              "attr3_2", "attr5_2", "attr1_3", "attr7_3", "attr4_3", "attr2_3", "attr3_3", "attr5_3"]

# print(df1[verif_val].count(), )
# print(wav6_9[verif_val].count())

In [30]:
# Renormaliser colonnes

col_norm = [["attr4_1", "sinc4_1", "intel4_1", "fun4_1", "amb4_1", 'shar4_1'], 
            ["attr3_2", "sinc3_2", "intel3_2", "fun3_2", "amb3_2"],
            ["attr4_2", "sinc4_2", "intel4_2", "fun4_2", "amb4_2", "shar4_2"],
            ["attr4_3", "sinc4_3", "intel4_3", "fun4_3", "amb4_3", "shar4_3"],
            ["attr2_3", "sinc2_3", "intel2_3", "fun2_3", "amb2_3", "shar2_3"]]


for col_list in col_norm:
    for col in col_list :
        df1.loc[wav6_9, col] = (df1.loc[wav6_9, col] - 1) * 100 / 9

    for idx_ligne in df1[wav6_9].index:
        ligne_vals = df1.loc[idx_ligne, col_list]
        somme_ligne = sum(ligne_vals)
        df1.loc[idx_ligne, col_list] = ligne_vals * 100 / somme_ligne
        
for col in col_norm:
    df1.loc[wav6_9, col] = df1.loc[wav6_9, col].round(2)


df1[wav6_9]["attr3_2"]

1846    19.05
1847    19.05
1848    19.05
1849    19.05
1850    19.05
        ...
3403    16.13
3404    16.13
3405    16.13
3406    16.13
3407    16.13
Name: attr3_2, Length: 1562, dtype: float64

In [34]:
df1.to_csv("Speed_Dating_Data.csv", index=False)

In [31]:
# Comparer les 6 attributs à travers les différents temps par homme et femme.
# Vérifiez le type de vos variables